services:
  web:
    build: .
    container_name: stream_data_light
    command: gunicorn -b 0.0.0.0:5000 -w 5 app:app
    expose:
      - "5000"
    volumes:
      - .:/app
      - ./twitch_data.db:/app/twitch_data.db
    env_file:
      - .env

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: stream_monitor
    volumes:
      - .:/app
      - ./twitch_data.db:/app/twitch_data.db
    env_file:
      - .env
    depends_on:
      - web
    restart: always

  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    container_name: update_db
    volumes:
      - .:/app
      - ./twitch_data.db:/app/twitch_data.db
    env_file:
      - .env
    restart: always
    depends_on:
      - web

  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner
    container_name: clean_stream_stats
    volumes:
      - .:/app
      - ./twitch_data.db:/app/twitch_data.db
    env_file:
      - .env
    restart: always
    depends_on:
      - web

  summary:
    build:
      context: .
      dockerfile: Dockerfile.summary
    container_name: update_stream_summary
    volumes:
      - .:/app
      - ./twitch_data.db:/app/twitch_data.db
    env_file:
      - .env
    restart: always
    depends_on:
      - web

  nginx:
    image: nginx:latest
    container_name: stream_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
